### PR TITLE
Add support for Spark 3.0.1

### PR DESCRIPTION
**Pull request by z4f1r0v**
# Add support for Spark 3.0.1

## Describe your change:

Adding support for the next major release of Spark.
Restructuring the `build.sbt` file so that different dependencies that have the Spark version in them are addressed separately.
Fixed problem with not reading last line in `sparkVersions` file

### Pull Request

* [x] PR description is meaningful.
* [x] There are no more than a few commits to merge.
* [x] There are no more than a few lines of code to review.

### Code style

* [x] Maximum line length does not require horizontal scrolling in Github
* [x] Compliant to FMT, ScalaStyle and ScalaFix

### Testing

* [ ] Unit tests for the added/modified code 
* [ ] Overall unit test coverage good
* [x] Unit tests are passing

### Dependencies

* [x] The safety plugin is happy
* [x] New dependencies do not have vulnerabilities

### Security

* [x] There is no known vulnerability being added to this project
* [x] Everything on this list is checked

### CODE REVIEW

**Comment by leobenkel** [comment]
Thank you @z4f1r0v ! 

Nothing broke ? Since Travis is dead, we dont have automated unit test anymore :( 

Were you able to test locally ?

**Comment by z4f1r0v** [comment]
I ran the `spark-cross-test.sh`. I think it is ok. You can judge for yourself.
[results.txt](https://github.com/leobenkel/ZparkIO/files/5951357/results.txt)

**Comment by leobenkel** [comment]
I dont see the tests running with spark 3.0.1 . When I search for `spark` in the log you sent, I only see `>>> spark version: 2.3.3` and `>>> spark version: 2.4.5`

**Comment by z4f1r0v** [comment]
Yes, @leobenkel, you are right. There is no 3.0.1. I have added the 3.0.1 also in the sbt, yet the script still doesn't pick it up. I ended up running `sbt -DsparkVersion="3.0.1" "; project root; clean; +test"` manually and was successful.
[results.txt](https://github.com/leobenkel/ZparkIO/files/5951778/results.txt)

**Comment by leobenkel** [comment]
ok cool ! Are you able to publish locally and use the library ? 
I wonder why the script is not working ...

**Comment by z4f1r0v** [comment]
@leobenkel, I fixed the problem with not reading the last version.
I also published locally the artefact and tested it on zparkio.g8 generated project. It works fine.

**Review by leobenkel — APPROVED** [review]
Awesome ! Thank you !

**Pull request merged**
