### PR TITLE
Move to GitHub Actions

### PR DESCRIPTION
**Pull request by z4f1r0v**
# Move to GitHub Actions

## Describe your change:

Porting the build and release from Travis to GitHub Actions. There are some actions necessary on @leobenkel's side:
 - [this](https://github.com/olafurpg/sbt-ci-release#secrets) needs to be in place for the release pipeline to work
 - Travis needs to be disconnected from the validation flow
 
I'm receiving pipeline output over on my fork. I guess the release can only be tested once the changes are merged :(

### Pull Request

* [x] PR description is meaningful.
* [x] There are no more than a few commits to merge.
* [ ] There are no more than a few lines of code to review.

### Code style

* [x] Maximum line length does not require horizontal scrolling in Github
* [x] Compliant to FMT, ScalaStyle and ScalaFix

### Testing

* [ ] Unit tests for the added/modified code 
* [ ] Overall unit test coverage good
* [x] Unit tests are passing

### Dependencies

* [x] The safety plugin is happy
* [ ] New dependencies do not have vulnerabilities

### Security

* [x] There is no known vulnerability being added to this project
* [ ] Everything on this list is checked

### CODE REVIEW

**Comment by z4f1r0v** [comment]
I got this on a squashed commit I made https://github.com/z4f1r0v/ZparkIO/runs/1870099317?check_suite_focus=true

**Comment by z4f1r0v** [comment]
So according to [this](https://github.com/scoverage/sbt-coveralls#add-an-environment-variable), I have added an environment variable. That one needs to be coming from Github secrets like the PGP and SONATYPE credentials. I'm not sure how to proceed here, @leobenkel? Should I make my own credentials for coveralls or do you want to share the token with me?

**Comment by leobenkel** [comment]
@z4f1r0v I can add those secrets as env variable to this repo , will that work ? We can always merge since it is now broken, it cant be worse ! haha

**Comment by leobenkel** [comment]
I copied all the secrets in the repo, would that work ?

**Review by leobenkel — APPROVED** [review]

**Pull request merged**
